project:
  type: book
  output-dir: ../docs

jupyter: lusee

book:
  title: "Forecasting Dark Ages Constraints for LuSEE"
  author: "Rugved Pund"
  date: today
  chapters:
    - index.qmd
    - 01_hosvd.qmd
    - 02_optimizer.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt


