paths:
  lusee_drive_dir: $LUSEE_DRIVE_DIR
  sky_dir: Simulations/SkyModels
  beam_dir: Simulations/BeamModels/LanderRegolithComparison/eight_layer_regolith/
  output_dir: $LUSEE_OUTPUT_DIR
    
sky:
  file: ULSA_32_ddi_smooth.fits

beam_config:
  type: fits
  default_file: hfss_lbl_3m_75deg.fits
  common_beam_angle: 40
  couplings:
    opposite:
      combinations: [[N,S], [E,W]]
      two_port: hfss_lbl_3m_75deg.2port.fits 
      sign: -1
  
beams: 
  N:
    angle: 0
  E:
    angle: -90
  S:
    angle: -180
  W:
    angle: -270

observation:
  long: 180
  lat: -10
  beams: [ N, S, E, W ]
  lunar_day: "2025-02-01 13:00:00 to 2025-02-28 13:00:00"
  dt: 3600 
  Tground: 0
  lmax: 32
  combinations: all
  freq:
    start: 1
    end: 51
    step: 1

simulation:
  output: ulsasim_angle10.fits
  cache_transform: lunar_day.pickle  
